/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	jobv1 "github.com/mohuishou/blog-code/02-k8s-operator/operator-kubebuilder-clientset/api/job/v1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeTests implements TestInterface
type FakeTests struct {
	Fake *FakeJobV1
	ns   string
}

var testsResource = schema.GroupVersionResource{Group: "job", Version: "v1", Resource: "tests"}

var testsKind = schema.GroupVersionKind{Group: "job", Version: "v1", Kind: "Test"}

// Get takes name of the test, and returns the corresponding test object, and an error if there is any.
func (c *FakeTests) Get(ctx context.Context, name string, options v1.GetOptions) (result *jobv1.Test, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(testsResource, c.ns, name), &jobv1.Test{})

	if obj == nil {
		return nil, err
	}
	return obj.(*jobv1.Test), err
}

// List takes label and field selectors, and returns the list of Tests that match those selectors.
func (c *FakeTests) List(ctx context.Context, opts v1.ListOptions) (result *jobv1.TestList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(testsResource, testsKind, c.ns, opts), &jobv1.TestList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &jobv1.TestList{ListMeta: obj.(*jobv1.TestList).ListMeta}
	for _, item := range obj.(*jobv1.TestList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested tests.
func (c *FakeTests) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(testsResource, c.ns, opts))

}

// Create takes the representation of a test and creates it.  Returns the server's representation of the test, and an error, if there is any.
func (c *FakeTests) Create(ctx context.Context, test *jobv1.Test, opts v1.CreateOptions) (result *jobv1.Test, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(testsResource, c.ns, test), &jobv1.Test{})

	if obj == nil {
		return nil, err
	}
	return obj.(*jobv1.Test), err
}

// Update takes the representation of a test and updates it. Returns the server's representation of the test, and an error, if there is any.
func (c *FakeTests) Update(ctx context.Context, test *jobv1.Test, opts v1.UpdateOptions) (result *jobv1.Test, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(testsResource, c.ns, test), &jobv1.Test{})

	if obj == nil {
		return nil, err
	}
	return obj.(*jobv1.Test), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeTests) UpdateStatus(ctx context.Context, test *jobv1.Test, opts v1.UpdateOptions) (*jobv1.Test, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(testsResource, "status", c.ns, test), &jobv1.Test{})

	if obj == nil {
		return nil, err
	}
	return obj.(*jobv1.Test), err
}

// Delete takes name of the test and deletes it. Returns an error if one occurs.
func (c *FakeTests) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(testsResource, c.ns, name, opts), &jobv1.Test{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeTests) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(testsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &jobv1.TestList{})
	return err
}

// Patch applies the patch and returns the patched test.
func (c *FakeTests) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *jobv1.Test, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(testsResource, c.ns, name, pt, data, subresources...), &jobv1.Test{})

	if obj == nil {
		return nil, err
	}
	return obj.(*jobv1.Test), err
}
