// Code generated by protoc-gen-go. DO NOT EDIT.
// source: product/app/v1/v1.proto

// package 命名规则: product.application.version

package v1

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CreateArticleReq struct {
	Title                string   `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Content              string   `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateArticleReq) Reset()         { *m = CreateArticleReq{} }
func (m *CreateArticleReq) String() string { return proto.CompactTextString(m) }
func (*CreateArticleReq) ProtoMessage()    {}
func (*CreateArticleReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_c6090e3745c002b5, []int{0}
}

func (m *CreateArticleReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateArticleReq.Unmarshal(m, b)
}
func (m *CreateArticleReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateArticleReq.Marshal(b, m, deterministic)
}
func (m *CreateArticleReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateArticleReq.Merge(m, src)
}
func (m *CreateArticleReq) XXX_Size() int {
	return xxx_messageInfo_CreateArticleReq.Size(m)
}
func (m *CreateArticleReq) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateArticleReq.DiscardUnknown(m)
}

var xxx_messageInfo_CreateArticleReq proto.InternalMessageInfo

func (m *CreateArticleReq) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *CreateArticleReq) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

type CreateArticleResp struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateArticleResp) Reset()         { *m = CreateArticleResp{} }
func (m *CreateArticleResp) String() string { return proto.CompactTextString(m) }
func (*CreateArticleResp) ProtoMessage()    {}
func (*CreateArticleResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_c6090e3745c002b5, []int{1}
}

func (m *CreateArticleResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateArticleResp.Unmarshal(m, b)
}
func (m *CreateArticleResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateArticleResp.Marshal(b, m, deterministic)
}
func (m *CreateArticleResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateArticleResp.Merge(m, src)
}
func (m *CreateArticleResp) XXX_Size() int {
	return xxx_messageInfo_CreateArticleResp.Size(m)
}
func (m *CreateArticleResp) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateArticleResp.DiscardUnknown(m)
}

var xxx_messageInfo_CreateArticleResp proto.InternalMessageInfo

type GetArticleReq struct {
	// @inject_tag: json:"id" form:"id" binding:"required"
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id" form:"id" binding:"required"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetArticleReq) Reset()         { *m = GetArticleReq{} }
func (m *GetArticleReq) String() string { return proto.CompactTextString(m) }
func (*GetArticleReq) ProtoMessage()    {}
func (*GetArticleReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_c6090e3745c002b5, []int{2}
}

func (m *GetArticleReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetArticleReq.Unmarshal(m, b)
}
func (m *GetArticleReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetArticleReq.Marshal(b, m, deterministic)
}
func (m *GetArticleReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetArticleReq.Merge(m, src)
}
func (m *GetArticleReq) XXX_Size() int {
	return xxx_messageInfo_GetArticleReq.Size(m)
}
func (m *GetArticleReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetArticleReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetArticleReq proto.InternalMessageInfo

func (m *GetArticleReq) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

type GetArticleResp struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetArticleResp) Reset()         { *m = GetArticleResp{} }
func (m *GetArticleResp) String() string { return proto.CompactTextString(m) }
func (*GetArticleResp) ProtoMessage()    {}
func (*GetArticleResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_c6090e3745c002b5, []int{3}
}

func (m *GetArticleResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetArticleResp.Unmarshal(m, b)
}
func (m *GetArticleResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetArticleResp.Marshal(b, m, deterministic)
}
func (m *GetArticleResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetArticleResp.Merge(m, src)
}
func (m *GetArticleResp) XXX_Size() int {
	return xxx_messageInfo_GetArticleResp.Size(m)
}
func (m *GetArticleResp) XXX_DiscardUnknown() {
	xxx_messageInfo_GetArticleResp.DiscardUnknown(m)
}

var xxx_messageInfo_GetArticleResp proto.InternalMessageInfo

type ListArticleTagsReq struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListArticleTagsReq) Reset()         { *m = ListArticleTagsReq{} }
func (m *ListArticleTagsReq) String() string { return proto.CompactTextString(m) }
func (*ListArticleTagsReq) ProtoMessage()    {}
func (*ListArticleTagsReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_c6090e3745c002b5, []int{4}
}

func (m *ListArticleTagsReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListArticleTagsReq.Unmarshal(m, b)
}
func (m *ListArticleTagsReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListArticleTagsReq.Marshal(b, m, deterministic)
}
func (m *ListArticleTagsReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListArticleTagsReq.Merge(m, src)
}
func (m *ListArticleTagsReq) XXX_Size() int {
	return xxx_messageInfo_ListArticleTagsReq.Size(m)
}
func (m *ListArticleTagsReq) XXX_DiscardUnknown() {
	xxx_messageInfo_ListArticleTagsReq.DiscardUnknown(m)
}

var xxx_messageInfo_ListArticleTagsReq proto.InternalMessageInfo

type ListArticleTagsResp struct {
	Tags                 []*Tag   `protobuf:"bytes,1,rep,name=tags,proto3" json:"tags,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListArticleTagsResp) Reset()         { *m = ListArticleTagsResp{} }
func (m *ListArticleTagsResp) String() string { return proto.CompactTextString(m) }
func (*ListArticleTagsResp) ProtoMessage()    {}
func (*ListArticleTagsResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_c6090e3745c002b5, []int{5}
}

func (m *ListArticleTagsResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListArticleTagsResp.Unmarshal(m, b)
}
func (m *ListArticleTagsResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListArticleTagsResp.Marshal(b, m, deterministic)
}
func (m *ListArticleTagsResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListArticleTagsResp.Merge(m, src)
}
func (m *ListArticleTagsResp) XXX_Size() int {
	return xxx_messageInfo_ListArticleTagsResp.Size(m)
}
func (m *ListArticleTagsResp) XXX_DiscardUnknown() {
	xxx_messageInfo_ListArticleTagsResp.DiscardUnknown(m)
}

var xxx_messageInfo_ListArticleTagsResp proto.InternalMessageInfo

func (m *ListArticleTagsResp) GetTags() []*Tag {
	if m != nil {
		return m.Tags
	}
	return nil
}

type Tag struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value                string   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Tag) Reset()         { *m = Tag{} }
func (m *Tag) String() string { return proto.CompactTextString(m) }
func (*Tag) ProtoMessage()    {}
func (*Tag) Descriptor() ([]byte, []int) {
	return fileDescriptor_c6090e3745c002b5, []int{6}
}

func (m *Tag) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Tag.Unmarshal(m, b)
}
func (m *Tag) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Tag.Marshal(b, m, deterministic)
}
func (m *Tag) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Tag.Merge(m, src)
}
func (m *Tag) XXX_Size() int {
	return xxx_messageInfo_Tag.Size(m)
}
func (m *Tag) XXX_DiscardUnknown() {
	xxx_messageInfo_Tag.DiscardUnknown(m)
}

var xxx_messageInfo_Tag proto.InternalMessageInfo

func (m *Tag) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *Tag) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func init() {
	proto.RegisterType((*CreateArticleReq)(nil), "product.app.v1.CreateArticleReq")
	proto.RegisterType((*CreateArticleResp)(nil), "product.app.v1.CreateArticleResp")
	proto.RegisterType((*GetArticleReq)(nil), "product.app.v1.GetArticleReq")
	proto.RegisterType((*GetArticleResp)(nil), "product.app.v1.GetArticleResp")
	proto.RegisterType((*ListArticleTagsReq)(nil), "product.app.v1.ListArticleTagsReq")
	proto.RegisterType((*ListArticleTagsResp)(nil), "product.app.v1.ListArticleTagsResp")
	proto.RegisterType((*Tag)(nil), "product.app.v1.Tag")
}

func init() { proto.RegisterFile("product/app/v1/v1.proto", fileDescriptor_c6090e3745c002b5) }

var fileDescriptor_c6090e3745c002b5 = []byte{
	// 366 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x52, 0xcf, 0x4e, 0xf2, 0x40,
	0x1c, 0x4c, 0xcb, 0xc7, 0xf7, 0xe7, 0x47, 0x20, 0xfd, 0xb6, 0x24, 0x36, 0xc4, 0x3f, 0xb8, 0x17,
	0x89, 0x09, 0xdd, 0x00, 0xf1, 0xe2, 0xc1, 0x44, 0x3c, 0x78, 0xf1, 0x54, 0x39, 0x99, 0x78, 0x58,
	0xca, 0x66, 0x59, 0x2d, 0xdd, 0xa5, 0xbb, 0xad, 0xf1, 0xea, 0x2b, 0xf8, 0x68, 0x1e, 0x7c, 0x01,
	0x1f, 0xc4, 0xd0, 0x82, 0xd2, 0x9a, 0xe8, 0x6d, 0x7f, 0xb3, 0x93, 0x99, 0xcc, 0x64, 0x60, 0x47,
	0x25, 0x72, 0x96, 0x86, 0x86, 0x50, 0xa5, 0x48, 0x36, 0x20, 0xd9, 0xc0, 0x57, 0x89, 0x34, 0x12,
	0xb5, 0xd6, 0x1f, 0x3e, 0x55, 0xca, 0xcf, 0x06, 0x9d, 0x5d, 0x2e, 0x25, 0x8f, 0x18, 0xa1, 0x4a,
	0x10, 0x1a, 0xc7, 0xd2, 0x50, 0x23, 0x64, 0xac, 0x0b, 0x36, 0x1e, 0x83, 0x73, 0x91, 0x30, 0x6a,
	0xd8, 0x79, 0x62, 0x44, 0x18, 0xb1, 0x80, 0x2d, 0x51, 0x1b, 0xea, 0x46, 0x98, 0x88, 0x79, 0x56,
	0xd7, 0xea, 0xfd, 0x0b, 0x8a, 0x03, 0x79, 0xf0, 0x27, 0x94, 0xb1, 0x61, 0xb1, 0xf1, 0xec, 0x1c,
	0xdf, 0x9c, 0xd8, 0x85, 0xff, 0x15, 0x0d, 0xad, 0xf0, 0x01, 0x34, 0x2f, 0x99, 0xd9, 0x52, 0x6d,
	0x81, 0x2d, 0x66, 0xb9, 0x64, 0x3d, 0xb0, 0xc5, 0x0c, 0x3b, 0xd0, 0xda, 0x26, 0x68, 0x85, 0xdb,
	0x80, 0xae, 0x84, 0xde, 0x40, 0x13, 0xca, 0x75, 0xc0, 0x96, 0xf8, 0x0c, 0xdc, 0x2f, 0xa8, 0x56,
	0xe8, 0x08, 0x7e, 0x19, 0xca, 0xb5, 0x67, 0x75, 0x6b, 0xbd, 0xc6, 0xd0, 0xf5, 0xcb, 0xa9, 0xfd,
	0x09, 0xe5, 0x41, 0x4e, 0xc0, 0x7d, 0xa8, 0x4d, 0x28, 0x47, 0x0e, 0xd4, 0xee, 0xd9, 0xe3, 0x3a,
	0xd2, 0xea, 0xb9, 0x8a, 0x99, 0xd1, 0x28, 0x65, 0xeb, 0x38, 0xc5, 0x31, 0x7c, 0xb5, 0xa0, 0x31,
	0x8e, 0x24, 0xbf, 0x66, 0x49, 0x26, 0x42, 0x86, 0x04, 0x34, 0x4b, 0xe1, 0x50, 0xb7, 0x6a, 0x55,
	0xed, 0xaf, 0x73, 0xf8, 0x03, 0x43, 0x2b, 0xec, 0x3e, 0xbd, 0xbc, 0x3d, 0xdb, 0x4d, 0xfc, 0x97,
	0xd0, 0x02, 0x3d, 0xb5, 0x8e, 0xd1, 0x2d, 0xc0, 0x67, 0x23, 0x68, 0xaf, 0xaa, 0x52, 0xaa, 0xb3,
	0xb3, 0xff, 0xdd, 0xb7, 0x56, 0xd8, 0xc9, 0x1d, 0x00, 0x7d, 0x38, 0x8c, 0x4f, 0x6e, 0x46, 0x5c,
	0x98, 0x79, 0x3a, 0xf5, 0x43, 0xb9, 0x20, 0x0b, 0x39, 0x4f, 0x85, 0x9e, 0xcb, 0x94, 0xc4, 0xec,
	0xa1, 0xaf, 0x12, 0x79, 0xc7, 0xf2, 0x31, 0x09, 0x52, 0x1e, 0xd6, 0xf4, 0x77, 0x3e, 0x94, 0xd1,
	0x7b, 0x00, 0x00, 0x00, 0xff, 0xff, 0xb7, 0x92, 0x54, 0xb9, 0x71, 0x02, 0x00, 0x00,
}
